executables: simulator_Q1 simulator_Q2 

simulator_Q1: simulator.cpp maxHeap1.cpp Doctor.cpp Patient.cpp
	g++ simulator.cpp maxHeap1.cpp Doctor.cpp Patient.cpp -o simulator_Q1

simulator_Q2: simulator.cpp maxHeap2.cpp Doctor.cpp Patient.cpp
	g++ simulator.cpp maxHeap2.cpp Doctor.cpp Patient.cpp -o simulator_Q2